version: '3.9'
services:
  node:
    image: app:node
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run nodemon
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgress
    environment:
      - PORT=${PORT}
    restart: always
    networks:
      - custom-bridge
    volumes:
      - .:/src/app
    env_file:
      - .env

  postgress:
    image: db:postgress
    container_name: db
    build: ./db/
    ports:
      - ${POSTGRES_PASSWORD}:${POSTGRES_PASSWORD}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure
    networks:
      - custom-bridge
    env_file:
      - .env
    volumes:
    - db-data:/var/lib/postgresql/data
    - db-logs:/logs

networks:
  custom-bridge:
    name: custom-bridge
    driver: bridge

volumes:
    db-data: { }
    db-logs: { }